spring.application.name=AFG-approv-achat
spring.datasource.url=jdbc:postgresql://10.25.10.151:5432/ACHAT_APPROV_PROD
spring.datasource.username=postgres
spring.datasource.password=Test@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false


ldap.username = intranet.mada
ldap.password = P@sswordBank2026
ldap.domainName = afgbank.com
ldap.serverName = 10.25.10.10

logging.level.org.springframework.security.ldap=DEBUG
logging.level.org.springframework.ldap=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

server.tomcat.max-part-count=500
server.tomcat.max-parameter-count=10000

storage.location=./pieces

spring.web.locale=fr_FR
spring.web.locale-resolver=fixed
